/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}", 
  ],
 theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#000000",
        "on-surface-variant": "#596064",
        "on-secondary-fixed-variant": "#525c6e",
        "primary-container": "#4e9af9",
        "on-surface": "#2c3437",
        "surface-dim": "#d4dbdf",
        "tertiary-container": "#deccfd",
        "tertiary": "#665882",
        "surface-container-low": "#f0f4f7",
        "surface-variant": "#dce4e8",
        "on-background": "#2c3437",
        "surface-container-high": "#e3e9ed",
        "on-secondary": "#f8f8ff",
        "surface-container-highest": "#dce4e8",
        "primary": "#0060b0",
        "on-secondary-container": "#495264",
        "secondary-dim": "#4a5365",
        "inverse-surface": "#0b0f10",
        "secondary-container": "#d9e3f8",
        "outline": "#747c80",
        "on-tertiary-container": "#50426b",
        "on-primary": "#f8f8ff",
        "on-error": "#fff7f6",
        "surface": "#f7f9fb",
        "inverse-on-surface": "#9a9d9f",
        "tertiary-fixed": "#deccfd",
        "primary-dim": "#00549b",
        "error-dim": "#67040d",
        "outline-variant": "#acb3b7",
        "inverse-primary": "#4e9af9",
        "surface-container": "#eaeff2",
        "on-error-container": "#6e0a12",
        "primary-fixed-dim": "#3d8dea",
        "surface-tint": "#0060b0",
        "on-tertiary-fixed-variant": "#594c75",
        "tertiary-dim": "#5a4c75",
        "on-primary-fixed-variant": "#00254a",
        "tertiary-fixed-dim": "#d0bfef",
        "on-primary-container": "#001a38",
        "background": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "error-container": "#fa746f",
        "on-secondary-fixed": "#364051",
        "secondary": "#565f72",
        "on-tertiary": "#fdf7ff",
        "error": "#a83836",
        "surface-bright": "#f7f9fb",
        "secondary-fixed": "#d9e3f8",
        "secondary-fixed-dim": "#cbd5ea",
        "primary-fixed": "#4e9af9",
        "on-tertiary-fixed": "#3c2f56"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};